[workspace]
changelog_update = true
git_release_enable = true
semver_check = true

[[package]]
name = "agentverse-server"
changelog_include = ["agentverse-core", "agentverse-api", "agentverse-storage", "agentverse-auth"]

[[package]]
name = "agentverse"
changelog_include = ["agentverse-core"]

