{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentverse.fullname" . }}
  labels:
    {{- include "agentverse.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "agentverse.databaseUrl" . | quote }}
  REDIS_URL: {{ include "agentverse.redisUrl" . | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  {{- if .Values.secrets.s3Endpoint }}
  S3_ENDPOINT: {{ .Values.secrets.s3Endpoint | quote }}
  S3_ACCESS_KEY: {{ .Values.secrets.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ .Values.secrets.s3SecretKey | quote }}
  {{- end }}
{{- end }}

